#!/bin/sh

#MUST BE NAMED COSMOS AND IN THE SAME DIR AS THE ACTUAL BINARIES!

if [ -x $0.`uname`-`arch` ]; then
	echo "Cosmos Autoselecter: Running $0.`uname`-`arch`"
	$0.`uname`-`arch` "$@"
	echo "Cosmos Autoselecter: Done"
else
	echo "Cosmos Autoselecter: Unknown or unsupported system: `uname`-`arch`"
fi
