#!/bin/sh

#MUST BE NAMED COSMOS AND IN THE SAME DIR AS THE ACTUAL BINARIES!

case "`uname`-`arch`" in
  Linux-i686|Linux-i586|Linux-i486|Linux-i386)
    echo "Cosmos Autoselecter: Running IA32 GNU/Linux Version"
    $0.Linux-i686 "$@"
    echo "Cosmos Autoselecter: Done"
    ;;

  Linux-ppc)
    echo "Cosmos Autoselecter: Running PPC GNU/Linux Version"
    $0.Linux-ppc "$@"
    echo "Cosmos Autoselecter: Done"
    ;;

  Darwin-ppc)
    echo "Cosmos Autoselecter: Running MacOS-X Version"
    $0.Darwin-ppc "$@"
    echo "Cosmos Autoselecter: Done"
    ;;

  *)
    echo "Unknown or unsupported system: `uname`-`arch`"
    exit 1
    ;;
esac

