const char *version = VERSION;

const char *credits =
"Primary Developer:\n"
"	Steaphan 'Stea' Greene - AKA Insomnia <stea@cs.binghamton.edu>\n"
"\n"
"Graphics and Art:\n"
"	Steaphan 'Stea' Greene - AKA Insomnia <stea@cs.binghamton.edu>\n"
"\n"
"Music:\n"
"	Wyatt Peterson <wyatt@binghamton.edu>\n"
"\n"
"Testers:\n"
"	Wyatt Peterson <wyatt@binghamton.edu>\n"
"	Sandor Szatmari <inkhead@inkhead.org>\n"
"\n"
"Intro Screen:\n"
"	Original Image Courtesy of NASA's JPL: http://jpl.nasa.gov/\n"
"\n"
"Graphics Software:\n"
"	Most Images Created by POV-Ray: http://www.povray.org/\n"
"	Other Images Created by The Gimp: http://www.gimp.org/\n"
"\n"
"Coding Software:\n"
"	GNU Compiler Collection: http://gcc.gnu.org/\n"
"	GNU Nano: http://www.nano-editor.org/\n"
"	Various GNU Utils: http://www.gnu.org/\n"
"\n"
"Interface Libraries:\n"
"	LibSDL: http://www.libsdl.org/\n"
"\n"
"Hardware Access Providers:\n"
"	Steaphan 'Stea' Greene - AKA Insomnia <stea@cs.binghamton.edu>\n"
"	Sandor Szatmari <inkhead@inkhead.org>\n"
"	Binghamton Comp. Sci. Dept: http://www.cs.binghamton.edu/\n"
"";
