const char *version = VERSION;

const char *credits =
"Primary Developer:\n"
"	Steaphan 'Stea' Greene - AKA Insomnia <stea@cs.binghamton.edu>\n"
"\n"
"Graphics and Art:\n"
"	Steaphan 'Stea' Greene - AKA Insomnia <stea@cs.binghamton.edu>\n"
"	Most Images Created by POV-Ray:\n"
"		http://www.povray.org/\n"
"	Other Images Created by The Gimp:\n"
"		http://www.gimp.org/\n"
"\n"
"Music:\n"
"	Wyatt Peterson <wyatt@binghamton.edu>\n"
"\n"
"Intro Screen:\n"
"	Image Courtesy of NASA's JPL:\n"
"		http://jpl.nasa.gov/\n"
"	Touched up by The Gimp:\n"
"		http://www.gimp.org/\n"
"\n"
"Testers:\n"
"	Wyatt Peterson <wyatt@binghamton.edu>\n"
"	Sandor Szatmari <inkhead@inkhead.org>\n"
"\n"
"Hardware Access Providers:\n"
"	Steaphan 'Stea' Greene - AKA Insomnia <stea@cs.binghamton.edu>\n"
"	Sandor Szatmari <inkhead@inkhead.org>\n"
"	Binghamton University Computer Science Dept:\n"
"		http://www.cs.binghamton.edu/\n"
"\n"
"Interface Libraries:\n"
"	SDL: http://www.libsdl.org/\n"
"";
