enum {PAGE_INVALID = 0,
	PAGE_ROOT,
	PAGE_NEW,
	PAGE_LOAD,
	PAGE_NET,
	PAGE_SYSOPT,
	PAGE_GALAXY,
	PAGE_SYSTEM,
	PAGE_PLANET,
	PAGE_MAX
	};

enum {BUTTON_INVALID = 0,
	BUTTON_CANCEL,
	BUTTON_ACCEPT,
	BUTTON_EXIT,
	BUTTON_OPTIONS,
	BUTTON_RANDOMIZE,
	BUTTON_RESETALL,
	BUTTON_CLEARALL,
	BUTTON_RESUMEGAME,
	BUTTON_NEWGAME,
	BUTTON_LOADGAME,
	BUTTON_NETWORKGAME,
	BUTTON_SYSTEMOPTIONS,
	BUTTON_QUITGAME,
	BUTTON_MAX
	};

void gui_init();
void gui_main();
