void gui_init_galaxy();
void gui_button_clicked_galaxy(int);
void panel_redraw_galaxy(SDL_Rect *);
void page_redraw_galaxy(SDL_Rect *);
void page_draw_galaxy();
void page_init_galaxy();
void page_update_galaxy();
void panel_clicked_galaxy(int, int, int);
void page_clicked_galaxy(int, int, int);
void mouse_moved_galaxy(int, int);
void mouse_released_galaxy();

void gui_init_system();
void gui_button_clicked_system(int);
void panel_redraw_system(SDL_Rect *);
void page_redraw_system(SDL_Rect *);
void page_draw_system();
void page_init_system();
void page_update_system();
void panel_clicked_system(int, int, int);
void page_clicked_system(int, int, int);
void mouse_moved_system(int, int);
void mouse_released_system();

void gui_init_planet();
void gui_button_clicked_planet(int);
void panel_redraw_planet(SDL_Rect *);
void page_redraw_planet(SDL_Rect *);
void page_draw_planet();
void page_init_planet();
void page_update_planet();
void panel_clicked_planet(int, int, int);
void page_clicked_planet(int, int, int);
void mouse_moved_planet(int, int);
void mouse_released_planet();
