void gui_init_galaxy();
void page_redraw_galaxy(SDL_Rect *);
void page_draw_galaxy();
void page_init_galaxy();
void page_cleanup_galaxy();
void page_update_galaxy();
void page_clicked_galaxy(int, int, int);
void mouse_moved_galaxy(int, int);
void mouse_released_galaxy();

void gui_init_system();
void page_redraw_system(SDL_Rect *);
void page_draw_system();
void page_init_system();
void page_cleanup_system();
void page_update_system();
void page_clicked_system(int, int, int);
void mouse_moved_system(int, int);
void mouse_released_system();

void gui_init_planet();
void page_redraw_planet(SDL_Rect *);
void page_draw_planet();
void page_init_planet();
void page_cleanup_planet();
void page_update_planet();
void page_clicked_planet(int, int, int);
void mouse_moved_planet(int, int);
void mouse_released_planet();

void gui_init_colony();
void panel_draw_colony();
void panel_init_colony();
void panel_cleanup_colony();
void panel_update_colony();
void panel_redraw_colony(SDL_Rect *);
void panel_clicked_colony(int, int, int);
void button_clicked_colony(int);
char *popstr(int, int mpop=0);
void mouse_moved_colony(int, int);
void mouse_released_colony();
